{% set version = "0.1.1" %}

package:
  name: pytest-beartype
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-beartype/pytest_beartype-{{ version }}.tar.gz
  sha256: 5b7d5344c2c23b930e56331c3cbb4b2b2a538dad7b5eea9ae6a40fe6d5faed47

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - beartype
    - pytest
    - python >=3.8

test:
  source_files:
    - tests
  requires:
    - coverage
    - mypy
    - pip
    - pytest
  imports:
    - pytest_beartype
  commands:
    - pip check
    - mypy -p pytest_beartype

about:
  home: https://github.com/tusharsadhwani/pytest-beartype
  summary: Pytest plugin to run your tests with beartype checking enabled.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - tusharsadhwani
